apiVersion: v1
kind: Secret
metadata:
  name: llm-load-generator-secrets
  namespace: default
type: Opaque
stringData:
  OTEL_ENDPOINT: "https://<ENV>.live.dynatrace.com/api/v2/otlp"
  DT_API_TOKEN: "<your-dynatrace-api-token>"
